services:
  node:
    build:
      context: .
      target: development
      args:
        USER_ID: ${USER_ID:-1000}
    env_file: .env
    tty: true
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${HTTP_PORT:-3080}:3080
      - ${NODEJS_DEBUG_PORT:-9229}:9229
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7.0.5
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_storage:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017
    healthcheck:
      test: >
        mongosh --quiet --eval "
        try {
          if (rs.status().myState === 1) exit(0);
        } catch (err) {
          rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});
        }
        exit(1);
        "
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  mongo_storage:
  node_modules: